services:
  vote:
    container_name: vote
    image: vote
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/serviceAccountKey.json
      - ENVIRONMENT=dev
      - PORT=8000
      - GCLOUD_PROJECT=assignment-3-454322
    ports:
      - "9080:8000"
    volumes:
      - ./cc_cloud_run:/app/cc_cloud_run:Z
      - ./static:/app/static:Z
      - ./template:/app/template:Z
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:Z

  db:
    image: firestore
    build:
      context: firestore
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - firestore:/app/.cache/firestore/emulators

volumes:
  firestore:
